<?php

/*
 * @file
 * Handles main functionality for Shippo module.
 */

/**
 * Implements hook_menu().
 */
function shippo_menu() {
  $items['admin/commerce/config/shipping/methods/shippo/edit'] = array(
    'title' => 'Edit',
    'description' => 'Configure the Shippo shipping method.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shippo_settings_form'),
    'access arguments' => array('administer shipping'),
    'file' => 'includes/shippo.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 0,
  );

  return $items;
}

/**
 * Implements hook_commerce_shipping_method_info().
 */
function shippo_commerce_shipping_method_info() {
  $shipping_methods['shippo'] = array(
    'title' => t('Shippo'),
    'description' => t('Quote rates from Shippo'),
  );

  return $shipping_methods;
}
